Models/Meetinginfo.cs
namespace MeetingApp.Models
{
    public class MeetingInfo
    {
        public int Id { get; set; }
        public string? Location { get; set; }
        public DateTime Date { get; set; }
        public int NumberOfPeople { get; set; }
    }
}

Models/Repository.cs
namespace MeetingApp.Models
{
    public static class Repository
    {
        private static List<UserInfo> _users = new();

        static Repository()
        {
            _users.Add(new UserInfo() { Id = 1, Name = "Ali", Email = "ali@gmail.com", Phone = "5457778899", WillAttend = true});
            _users.Add(new UserInfo() { Id = 2, Name = "Ahmet", Email = "ahmet@gmail.com", Phone = "5455730649", WillAttend = false });
            _users.Add(new UserInfo() { Id = 3, Name = "Hasan", Email = "hasan@gmail.com", Phone = "5454215612", WillAttend = true });
            
        }




        public static List<UserInfo> Users
        {
            get
            {
                return _users;
            }
        }



    public static void CreateUSer(UserInfo user)
    {
            user.Id = Users.Count + 1;
            _users.Add(user);
    }
    public static UserInfo? GetById(int id)
    {
            return _users.FirstOrDefault(user => user.Id == id);
    }

    }
}

Models/UserInfo.cs
using System.ComponentModel.DataAnnotations;

namespace MeetingApp.Models
{
    public class UserInfo
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="İsim Bilgisi Zorunludur.")]
        public string? Name { get; set; }
        [Required(ErrorMessage = "Telefon Bilgisi Zorunludur.")]
        public string? Phone { get; set; }
        [Required(ErrorMessage = "Mail Bilgisi Zorunludur.")]
        [EmailAddress(ErrorMessage = "Hatalı Mail Bilgisi.")]
        public string? Email { get; set; }
        [Required(ErrorMessage = "Katılım Bilgisi Zorunludur.")]
        public bool WillAttend { get; set; }
    }
}

Controllers/HomeController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            int saat = DateTime.Now.Hour;
            // ViewBag.Selam = saat > 12 ? "İyi Günler" : "Günaydın";
            // ViewBag.Username = "OĞUZHAN";
             ViewData["Selam"] = saat > 12 ? "İyi Günler" : "Günaydın";
          //   ViewData["Username"] = "OĞUZHAN";
            var meetingInfo = new MeetingInfo() 
            { 
                Id = 1,
                Location = "Adana, Nazım Hikmet Kültür Merkezi",
                Date = new DateTime(2024,06,06,20,0,0),
                NumberOfPeople = 100
            };
            return View(meetingInfo);
        }
    }
}

Controllers/MeetingController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{

    public class MeetingController : Controller
    {


        [HttpGet]
        public IActionResult Apply()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Apply(UserInfo model)
        {
            if (ModelState.IsValid)
            {
                Repository.CreateUSer(model);
                ViewBag.UserCount = Repository.Users.Where(info => info.WillAttend == true).Count();
                return View("Thanks", model);
            }else 
            {
                return View(model);
            }

        }




        [HttpGet]
        public IActionResult List()
        {

            return View(Repository.Users);
        }

        public IActionResult Details(int id)
        {
            return View(Repository.GetById(id));
        }


    }
}

Views/Home/Index.cshtml
@model MeetingInfo;
@{
    ViewBag.Title = "Toplantı Başvuru ";
    Layout = "_Layout2";
}
<main class="text-center">
<h1 class="h4">@ViewData["Selam"]</h1>
<p>TOPLANTI KATILIM DURUMUNUZU BİLDİRİNİZ </p>
<div class="card my-2">
    <ul class="list-group list-group-flush">
        <li class="list-group-item">@Model.Location Konumunda</li>
        <li class="list-group-item">@Model.Date.ToString("dd/MM/yyyy HH:mm:ss") Tarihinde Gerçekleşecek</li>
        <li class="list-group-item">@Repository.Users.Where(i=>i.WillAttend == true).Count() Katılımcı</li>
    </ul>
</div>
<a asp-controller="Meeting" asp-action="Apply" class="btn btn-sm btn-outline-primary">BAŞVURU YAP</a>
</main>

Views/Meeting/Apply.cshtml
@model  UserInfo
@{
    ViewBag.Title = "Başvuru Formu";
}
<h1 class="h4">TOPLANTI KATILIM FORMU</h1>
<form asp-action="Apply" method="post" novalidate>
<div asp-validation-summary="All"></div>
    <div class="mb-3">
        <label asp-for="Name" class="form-label">İsim</label>
        <input asp-for="Name" class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="Phone" class="form-label">Telefon</label>
        <input asp-for="Phone"  class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email"  class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="WillAttend" class="form-label">Katılacak Durumu </label>
        <select asp-for="WillAttend" class="form-select">
            <option value="">Seçiniz</option>
            <option value="true">Evet, Geliyorum</option>
            <option value="false">Hayır, Gelmiyorum</option>
        </select>
    </div>

    <button class="btn btn-primary" type="submit">Kaydet</button>
</form>

Views/Meeting/Details.cshtml
@model  UserInfo
@{
    ViewBag.Title = "Başvuru Detayı";
}
@{
    var className = @Model.WillAttend == true ? "primary" : "danger";
    //var durum = className == "primary" ? "Katılıyor" : "Katılmıyor";
}

<main class="text-center">
    <h1 class="h4">Başvuru Detayı</h1>
    <p>
        <span class="badge text-bg-@className">
            @if(Model.WillAttend == true)
            {
                <text>Katılıyor</text>
            }else
            {
                <text>Katılmıyor</text>
            }
        </span>
    </p>
    <p>İsim : @Model.Name</p>
    <p>Mail : @Model.Email</p>
    <p>Telefon : @Model.Phone</p>
    <a asp-controller="Meeting" asp-action="List" class="btn btn-outline-@className">Katılımcı Listesi</a>

</main>

Views/Meeting/List.cshtml
@model  List<UserInfo>
@{
    ViewBag.Title = "TOPLANTI KATILIM LİSTESİ";
}
<main class="text-center">
    <h1 class="h4">TOPLANTI KATILIM LİSTESİ</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Ad</td>
                <td>Katılım Durumu</td>
                <td>Detay</td>
            </tr>
        </thead>
        <tbody>
            @{int i = 0;}
            @foreach(var user in Model)
            {
                var durum = user.WillAttend == true ? "Evet" : "Hayır";
                var className = user.WillAttend == true ? "table-success" : "table-danger";
                if(user.WillAttend == true)
                {
                    i++;
                }
                <tr class="@className">
                    <td>@user.Name</td>
                    <td>@durum</td>
                    <td><a class="btn btn-sm btn-primary" href="/meeting/details/@user.Id">Detay</a></td>
                </tr>
            }
    
        </tbody>
    </table>
    <div class="card">
        <div class="card-body">
            <span>Katılımcı Sayısı : @i</span>
        </div>
    </div>
</main>

Views/Meeting/Thanks.cshtml
@model  UserInfo
@{
    ViewBag.Title = "Başvuru Özeti";

}
<main class="text-center">
    <h1 class="h4">Başvuru Özeti</h1>


    @if(Model.WillAttend == true)
    {
        <p>Teşekkürler, @Model.Name Toplantıya Sizinle Birlikte @ViewBag.UserCount kişi katılıyor</p>
        <a class="btn btn-outline-primary btn-sm" href="/meeting/list">Katılımcıları Listele</a>
    }else
    {
        <p>@Model.Name, katılmıyor </p>
        <a class="btn btn-outline-primary btn-sm" href="/meeting/apply">Tekrar Başvur</a>
    }

</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/styles.css" />

    <title>@ViewBag.Title - MeetingApp</title>
</head>

<body>
    <div class="bg-primary text-white p-2 text-center">MeetingApp</div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css"
        integrity="sha512-jnSuA4Ss2PkkikSOLtYs8BlYIeeIK1h99ty4YfvRPAlzr377vr3CXDb7sb7eEEBYjDtcYj+AjBH3FLv5uSJuXg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>@ViewBag.Title - MeetingApp</title>
</head>

<body>
    <div class="bg-primary text-white p-2 text-center">MeetingApp</div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto text-center">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>